# version: '3.8'

services:
  react-app:
    container_name: react-app
    build: ./my project
    ports:
      - "80:5173"
    working_dir: /app
    volumes:
      - ./my project:/app
      - /app/node_modules
    command: ["bun", "run", "dev"]  # รัน React ด้วย bun
    stdin_open: true
    tty: true
    depends_on:
      - server
      - db
    networks:
      - my_app

  server:
    container_name: snake-server
    build: ./server
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./server:/app
      # - /app/node_modules
      - ./server/.env:/app/.env  # Mount ไฟล์ .env เข้าไปในคอนเทนเนอร์
    command: ["bun", "run", "server.ts"]  # รันเซิร์ฟเวอร์ด้วย bun
    restart: always
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_HOST: db  # ใช้ชื่อ service แทน localhost
      DB_PORT: 5432
      DB_NAME: ct648
    depends_on:
      - db
    networks:
      - my_app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ct648
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my_app

networks:
  my_app:
    driver: bridge